### ISSUE TITLE
Metodo de overwrite do Styled-components

### ISSUE THREAD

**Issue by vacom** [antoniojps/avocado-client#1]
Notei que algum dos componentes básicos utilizando styled-components são feitos de com método de overwrite o exemplo que esta no Emoji (https://github.com/antoniojps/avocado-client/blob/master/src/elements/Emoji.js). 

Este método é bom quando importamos uma lib de ui externa onde queremos alterar os seus estilos.

Então para uma melhor performance e menos boilerplate o exemplo do emoji podia ficar na seguinte forma:

```javascript
const Emoji = styled.span`
  display: inline-flex;
  font-size: 2rem;
  padding-right: 1rem;
`;

Emoji.defaultProps = {
  label: "emoji",
  emoji: "🥑"
};

Emoji.propTypes = {
  label: PropTypes.string.isRequired,
  emoji: PropTypes.string.isRequired
};

export default Emoji;
```

Desta forma nem é preciso preocupar com atributos genéricos como className, role, aria-label, já que tudo isso pertence ao próprio elemento tag.

**Comment by antoniojps** [comment]
O objetivo deste componente era não ter que estar sempre a escrever os atributos genéricos (role, aria-label) requisitados pela regra [jsx-a11y/accessible-emoji](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/accessible-emoji.md?fbclid=IwAR0D6QtB89y-D97UNBXaD1lThySKjyO6i7h5lG1Dq5Xgu-eVr__HVZJB51E).

Concordo que utilizar um _styled component_ é a melhor solução contudo o _eslint_ não reconhece este como um elemento _span_ e para dar disable a esta rule é necessário fazer eject do projecto e acho que um Emoji não o justifica.

De qualquer forma foi implementado o componente como styled component com os atributos default estabelecidos através do método [**.attrs**](https://www.styled-components.com/docs/api#attrs) que desconhecia, obrigado 😄

[Fix #1](https://github.com/antoniojps/avocado-client/commit/38d8091e03076add9bd77322a4a0b4b9c7c603e6)
